dist: trusty
sudo: required

language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      g++-7
      gcc-7
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq
script:
  - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE="Debug" -DTRAVIS="me too thanks" .. && make && ./unit-tests
